FROM python:3.8.0-slim
LABEL version=0.1.0 \
      metadata="The base image for async weather api code" \
      maintainer="Volodymyr Yahello <vyahello@gmail.com>"
RUN pip install --no-cache-dir --upgrade pip && \
    apt-get update && \
    apt-get autoclean -y